site_name: Technogi Handbook

theme:
  name: material
  favicon: assets/favicon.png
  features:
    - tabs

plugins:
  - search
  #- mkpdfs:
  #    author: Juan Francisco Alvarez Urquijo
  #    company: Technogi

markdown_extensions:
  - pymdownx.superfences
  - admonition

nav:
  - Technogi Handbook: index.md
  - About:
      - History: about/history.md
      #- Founders:
